sudo: required

language: python # => 1

python: # => 2
  - "3.6.2"

services:
  docker

before_install:

  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script: # => 7
      - python manage.py test
      - docker build -t zero0virus/song_api_docker_web .
      - docker tag zero0virus/song_api_docker_web registry.heroku.com/$HEROKU_APP_NAME/web
    
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push zero0virus/song_api_docker_web;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME

  branch: master
