language: python # => 1
    python: # => 2
      - "3.6.2"
    env: # => 4
      -DJANGO=2.0.* DRF=3.7.*
    install: # => 5
      - pip install -r requirements.txt
    before_script: # => 6
      - mysql -e 'create database test;' -u root
    script: # => 7
      - python manage.py test
