version: '3'

services:
  web:
    build: .
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:$PORT"
    container_name: song_api_docker
    volumes:
      - .:/song-api-docker
    ports:
      - "8000:8000"
